### PR TITLE
update

### PR DESCRIPTION
**Pull request by LinguList**
@tresoldi, this is my final version. I'd like to ask you to check it and make minor edits, in case you see things like missing captions, or other things. But please only minor edits, like replacing a figure, changing the size of a figure, no edits on text. Once you are through this, we will upload this this Wednesday to hcommons.

### CODE REVIEW

**Comment by tresoldi** [comment]
Oh, the synchrony... I had reserved the morning to work on this, an that is what I was doing: https://github.com/digling/calcblog/commits/master

I'll see to merge your changes manually.

**Comment by LinguList** [comment]
Okay, consider the work as finished now. You can see from my changes that there is some substantial work needed, but also that this just needs to be done manually. I also corrected the Python code, which was no longer running.

**Comment by LinguList** [comment]
My final version, to avoid misunderstandings, is calcblog-edit.pdf and calcblog-edit.tex

**Comment by tresoldi** [comment]
I was compiling a list of questions, but the main one is: should we have typed out bibliography, as now (which still needs some homogenization) or should we move to bib(la)tex? And, it this case, should we have a single bibliography (I would be against).

**Comment by LinguList** [comment]
No, consider the work as finished, and have a look at the doc I prepared.

**Comment by LinguList** [comment]
so to clarify: the homogenization of the bibliograhpy is not needed, as we are not a journal. But if you spot things like, e.g., bold font in bibliographies, then yes, please replace them by normal font. And look at figures to maybe resize them or replace them with a better version, or check for clubs and widows, etc.

**Comment by tresoldi** [comment]
Ok, good. I've finished manually merging our changes, I'll keep working on it during the afternoon and deliver it to you at the end of the day at most.

**Comment by LinguList** [comment]
What did you merge? I mean, I submitted a new file, that is called `calcblog-edit.tex`, and of which I think it is fine, I was just asking you for a final check on minor things.

**Comment by tresoldi** [comment]
I was just about to push my local changes, whereI was manually fixing many things, like bibliographies, spaces between brackets and parentheses, etc. That's why I was speaking of synchronicity... 

I had to use meld to merge them, it would too much of a hassle otherwise. I've finished this "merge", I am doing some minor cosmetic things and will take a glance at the PDF later. But it is almost done.

**Comment by LinguList** [comment]
Alright. I just do not want any other changes on layout, or similar, as I spent enough time on this today. I didn't expect you to start working on anything, since I didn't see any changes since March, so I decided to finish it, in order to have it off the table.

**Comment by tresoldi** [comment]
No absolutely nothing to the layout. Just minor stuff which are still pending, such as trailing spaces, table numbers, etc.

And I had started this morning, you can see from my commits, I suppose I should have told you. I had a mental note to start doing it as soon as CLICS was finished, after the last meeting.

**Pull request merged**
